#!/usr/bin/env node
/**
 * Generates `src/styles/tokens.css` from `src/design/tokens.js`.
 *
 * Why generate rather than hand-write: the same 32 values have to appear as CSS
 * custom properties (what the browser paints), as Tailwind colour names (what
 * components write), and as hex (what the contrast test proves). Three
 * hand-maintained copies of one palette drift — usually silently, usually in the
 * theme nobody has open. One source, two derived artefacts, and a test that fails
 * if the derived one is stale.
 *
 * Channels are emitted space-separated (`245 249 252`, not `#F5F9FC`) so Tailwind
 * can fill its `<alpha-value>` slot: `bg-surface/80` needs `rgb(var(--surface) / 0.8)`,
 * which a hex custom property cannot express.
 *
 *   node scripts/generate-tokens.mjs           write the file
 *   node scripts/generate-tokens.mjs --check   exit 1 if it is stale (CI, tests)
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

import { THEMES, tokensFor } from '../src/design/tokens.js';
import { hexToRgb } from '../src/design/contrast.js';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
export const OUTPUT_PATH = join(ROOT, 'src/styles/tokens.css');

const HEADER = `/* GENERATED by scripts/generate-tokens.mjs — do not edit.
 * Source of truth: src/design/tokens.js. Run \`npm run tokens\` after changing it.
 *
 * Light is the default on :root so a document with no theme class still paints
 * correctly. Dark is applied by a class, not by a media query, so the theme
 * provider can offer light / dark / system rather than only what the OS says. */\n`;

const block = (selector, tokens, extra = '') =>
  `${selector} {\n` +
  (extra ? `  ${extra}\n` : '') +
  Object.entries(tokens)
    .map(([name, hex]) => `  --${name}: ${hexToRgb(hex).join(' ')}; /* ${hex} */`)
    .join('\n') +
  '\n}\n';

export function renderTokensCss() {
  const [light, dark] = THEMES;

  return [
    HEADER,
    block(':root', tokensFor(light), 'color-scheme: light;'),
    '',
    block('.dark', tokensFor(dark), 'color-scheme: dark;'),
  ].join('\n');
}

const isMain = process.argv[1] === fileURLToPath(import.meta.url);

if (isMain) {
  const next = renderTokensCss();
  const check = process.argv.includes('--check');
  const current = (() => {
    try {
      return readFileSync(OUTPUT_PATH, 'utf8');
    } catch {
      return null;
    }
  })();

  if (check) {
    if (current !== next) {
      console.error(
        'src/styles/tokens.css is stale. Run `npm run tokens` and commit the result.'
      );
      process.exit(1);
    }
    console.log('src/styles/tokens.css is in sync with src/design/tokens.js.');
  } else {
    writeFileSync(OUTPUT_PATH, next);
    console.log(`Wrote ${OUTPUT_PATH}`);
  }
}
