-- =============================================================================
-- Migration: 000_baseline.sql
-- Purpose:   Create the two tables the entire product runs on — `properties`
--            and `bookings` — plus the legacy `settings` table and the shared
--            `update_updated_at_column()` trigger function.
-- Date:      2026-09-02
-- =============================================================================
--
-- WHY THIS FILE EXISTS
--
-- `properties` and `bookings` predate the migrations folder. Until now the
-- repository could not rebuild its own database: migrations 001-009 all ALTER
-- tables that no migration ever CREATEs, so the chain fails on statement one
-- against an empty database. That means no staging environment, no local
-- reproduction, and no way to reason about live schema from the code.
--
-- HOW THIS FILE WAS BUILT  ⚠️  READ BEFORE APPLYING
--
-- It is a *reconstruction*, not a dump. No live-schema export existed at the
-- time of writing, so every column below is derived from evidence in the
-- repository:
--
--   • columns the application reads or writes (AdminProperties.jsx form state,
--     the booking inserts in ServicesMain.jsx and Contact.jsx, AdminBookings.jsx,
--     BookingDetailModal.jsx, exportUtils.js)
--   • types implied by later migrations — e.g. 002 declares
--     `property_id INTEGER REFERENCES properties(id)`, which fixes
--     `properties.id` as an integer identity column, not a uuid
--
-- The 2026-09-01 audit counted 24 columns on `properties` and 25 on `bookings`.
-- This file may therefore differ from production by a column or two. Every
-- statement is idempotent and additive — `CREATE TABLE IF NOT EXISTS` and
-- `ADD COLUMN IF NOT EXISTS` — so applying it against the live database cannot
-- drop or retype anything. Worst case it adds a column production lacked.
--
-- 🔑 OWNER STEP: after applying, run the drift query at the bottom of this file
-- and reconcile any differences. Until that is done, treat this baseline as
-- "close" rather than "correct".
--
-- =============================================================================


-- -----------------------------------------------------------------------------
-- 0. Shared trigger function
--
-- 003a's admin_settings trigger calls this and never defines it — another way
-- the chain could not replay. Defined here, once, for every table that wants it.
-- -----------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;


-- -----------------------------------------------------------------------------
-- 1. properties
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.properties (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at    TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at    TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

  -- Listing
  title         TEXT NOT NULL,
  description   TEXT,
  price         NUMERIC(14, 2),

  -- Classification. `purpose` is sale|rent; `property_type` is constrained by
  -- purpose in the admin UI (sale: land|residential|commercial,
  -- rent: apartment|villa|office) and is deliberately left unconstrained here
  -- so the vocabulary can change without a migration.
  property_type TEXT,
  purpose       TEXT    DEFAULT 'sale',
  status        TEXT    DEFAULT 'available',

  -- Location
  location      TEXT,
  address       TEXT,

  -- Specification
  bedrooms      INTEGER,
  bathrooms     NUMERIC(4, 1),
  area_sqft     NUMERIC(12, 2),
  lot_size_sqft NUMERIC(12, 2),

  -- Features
  has_pool      BOOLEAN DEFAULT FALSE,
  has_garden    BOOLEAN DEFAULT FALSE,
  featured      BOOLEAN DEFAULT FALSE,

  -- Media and amenities are JSONB arrays of Cloudinary URLs / free-text labels
  images        JSONB   DEFAULT '[]'::jsonb,
  amenities     JSONB   DEFAULT '[]'::jsonb
);

-- Additive guards: if production already has `properties`, these fill in only
-- what is missing and touch nothing that exists.
ALTER TABLE public.properties
  ADD COLUMN IF NOT EXISTS updated_at    TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  ADD COLUMN IF NOT EXISTS purpose       TEXT DEFAULT 'sale',
  ADD COLUMN IF NOT EXISTS status        TEXT DEFAULT 'available',
  ADD COLUMN IF NOT EXISTS lot_size_sqft NUMERIC(12, 2),
  ADD COLUMN IF NOT EXISTS has_pool      BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS has_garden    BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS featured      BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS images        JSONB DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS amenities     JSONB DEFAULT '[]'::jsonb;

-- Every public listing query filters or sorts on these.
CREATE INDEX IF NOT EXISTS idx_properties_status     ON public.properties(status);
CREATE INDEX IF NOT EXISTS idx_properties_purpose    ON public.properties(purpose);
CREATE INDEX IF NOT EXISTS idx_properties_featured   ON public.properties(featured) WHERE featured = TRUE;
CREATE INDEX IF NOT EXISTS idx_properties_created_at ON public.properties(created_at DESC);

DROP TRIGGER IF EXISTS update_properties_updated_at ON public.properties;
CREATE TRIGGER update_properties_updated_at
  BEFORE UPDATE ON public.properties
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();


-- -----------------------------------------------------------------------------
-- 2. bookings
--
-- One table serves three intake paths, discriminated by `type`:
--   'viewing'      — property viewing request      (ServicesMain.jsx)
--   'consultation' — valuation / advisory request  (ServicesMain.jsx)
--   'contact'      — general enquiry               (Contact.jsx)
--
-- `type` is NOT NULL with no default. That is load-bearing: the service form
-- omitted it for months and every submission silently failed to save.
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.bookings (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at    TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

  type          TEXT NOT NULL,

  -- Contact details supplied by the prospect
  name          TEXT NOT NULL,
  email         TEXT,
  phone         TEXT,

  -- Viewing / consultation path
  service       TEXT,   -- finer-grained than `type`: viewing|valuation|consultation|management
  viewing_type  TEXT,   -- physical|virtual
  appointment_at TIMESTAMP WITH TIME ZONE,

  -- General-enquiry path
  subject       TEXT,
  inquiry_type  TEXT,
  property_type TEXT,
  location      TEXT,
  budget        TEXT,

  notes         TEXT
);

ALTER TABLE public.bookings
  ADD COLUMN IF NOT EXISTS service        TEXT,
  ADD COLUMN IF NOT EXISTS viewing_type   TEXT,
  ADD COLUMN IF NOT EXISTS appointment_at TIMESTAMP WITH TIME ZONE,
  ADD COLUMN IF NOT EXISTS subject        TEXT,
  ADD COLUMN IF NOT EXISTS inquiry_type   TEXT,
  ADD COLUMN IF NOT EXISTS property_type  TEXT,
  ADD COLUMN IF NOT EXISTS location       TEXT,
  ADD COLUMN IF NOT EXISTS budget         TEXT,
  ADD COLUMN IF NOT EXISTS notes          TEXT;

CREATE INDEX IF NOT EXISTS idx_bookings_created_at     ON public.bookings(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_bookings_type           ON public.bookings(type);
CREATE INDEX IF NOT EXISTS idx_bookings_appointment_at ON public.bookings(appointment_at);

-- Note: `status`, `priority`, `client_id`, `property_id`, and the admin
-- workflow columns are added by 002; the identity columns are retyped to
-- uuid by 009. They are deliberately not duplicated here.


-- -----------------------------------------------------------------------------
-- 3. settings (legacy Cloudinary credentials)
--
-- Superseded by `admin_settings` and removed by 010. Recreated here only so the
-- chain replays; a fresh database gets an empty table that 010 then drops.
--
-- ⚠️ In production this table held a Cloudinary `api_secret` readable by the
-- anon key. No secret column is recreated here — see 010 and Phase 0.2.
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.settings (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at    TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at    TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  cloud_name    TEXT,
  upload_preset TEXT
);


-- =============================================================================
-- 🔑 OWNER DRIFT CHECK — run against production after applying
--
-- Compare the result with the column lists above. Anything present in
-- production and absent here is a column this file must gain; anything absent
-- in production is a column this file just added (harmless, but worth knowing).
--
--   SELECT table_name, column_name, data_type, is_nullable, column_default
--     FROM information_schema.columns
--    WHERE table_schema = 'public'
--      AND table_name IN ('properties', 'bookings', 'settings')
--    ORDER BY table_name, ordinal_position;
--
-- =============================================================================
